from typing import Any, Literal

from pydantic import BaseModel, Field


class TaskItem(BaseModel):
    id: str = Field(..., description="Unique ID for the task (e.g., 'task_1')")
    title: str = Field(..., description="Short title for UI display")
    description: str = Field(..., description="Detailed instruction for the worker")
    tool_name: str = Field(
        ...,
        description="Which tool/skill to use (e.g., 'submit_background_ingestion_job')",
    )
    tool_args: dict[str, Any] = Field(
        default_factory=dict, description="Arguments for the tool"
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="List of task IDs that must finish before this one starts",
    )
    assigned_model: str = Field(
        "gpt-4-turbo", description="The model to use for this specific task"
    )
    status: Literal["pending", "approved", "running", "completed", "failed"] = "pending"
    result: str | None = None


class ExecutionPlan(BaseModel):
    """
    A structured plan of action generated by the Architect Agent.
    """

    plan_id: str = Field(..., description="Unique ID for the plan")
    title: str = Field(..., description="High-level title of the plan")
    rationale: str = Field(..., description="Reasoning behind the plan structure")
    tasks: list[TaskItem] = Field(..., description="List of tasks to execute")

    # Metadata for Knowledge Base
    original_user_query: str | None = None
    created_at: str | None = None
    is_template: bool = False  # If true, this is a reusable template
