from __future__ import annotations

PROVIDER_PROTOCOL_RUNTIME_VERSION = "v2"
CANONICAL_SCHEMA_VERSION = "2026-03-07"
PROTOCOL_PROFILE_SCHEMA_VERSION = "2026-03-07"

__all__ = [
    "PROVIDER_PROTOCOL_RUNTIME_VERSION",
    "CANONICAL_SCHEMA_VERSION",
    "PROTOCOL_PROFILE_SCHEMA_VERSION",
]
