"""create secretary tables

Revision ID: 20260107_02b
Revises: 20260107_01
Create Date: 2026-01-07 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260107_02b'
down_revision = '20260107_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create SecretaryPhase table
    op.create_table('secretary_phase',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Phase Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Internal description'),
    sa.Column('enable_retrieval', sa.Boolean(), nullable=False, comment='Enable RAG/Qdrant Retrieval'),
    sa.Column('enable_ingest', sa.Boolean(), nullable=False, comment='Enable Memory Ingestion'),
    sa.Column('enable_compression', sa.Boolean(), nullable=False, comment='Enable History Compression'),
    sa.Column('policy_config', sa.JSON(), nullable=False, comment='Detailed Policy Configuration'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secretary_phase_name'), 'secretary_phase', ['name'], unique=True)

    # Create UserSecretary table
    op.create_table('user_secretary',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner User ID'),
    sa.Column('current_phase_id', sa.UUID(), nullable=False, comment='Current Capability Phase'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Secretary Name'),
    sa.Column('custom_instructions', sa.Text(), nullable=True, comment='User-defined system prompt additions'),
    sa.Column('ui_preferences', sa.JSON(), nullable=True, comment='UI specific settings'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_phase_id'], ['secretary_phase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_secretary_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_secretary')
    op.drop_index(op.f('ix_secretary_phase_name'), table_name='secretary_phase')
    op.drop_table('secretary_phase')
    # ### end Alembic commands ###
