"""create agent plugin table

Revision ID: 20260107_01
Revises: 20260106_09_add_assistant_search_index
Create Date: 2026-01-07 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260107_01'
down_revision = '20260106_09_add_assistant_search_index'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_plugin',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Plugin unique identifier'),
    sa.Column('display_name', sa.String(length=200), nullable=True, comment='Display name'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Semantic version'),
    sa.Column('description', sa.Text(), nullable=True, comment='Function description'),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='Icon URL'),
    sa.Column('module_path', sa.String(length=500), nullable=False, comment='Python module import path'),
    sa.Column('config_schema', sa.JSON(), nullable=True, comment='Configuration JSON Schema'),
    sa.Column('capabilities', sa.JSON(), nullable=True, comment='Capability tags list'),
    sa.Column('owner_id', sa.UUID(), nullable=True, comment='Owner ID'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='Visibility: PUBLIC, PRIVATE, SHARED'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Is system built-in'),
    sa.Column('is_approved', sa.Boolean(), nullable=False, comment='Is approved'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_plugin_name'), 'agent_plugin', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_plugin_name'), table_name='agent_plugin')
    op.drop_table('agent_plugin')
    # ### end Alembic commands ###
